title: Roman Martyrology
name: Roman Martyrology 
author: Veronica Brandt
markdown: redcarpet
highlighter: pygments
#url: http://localhost:4000
url: http://www.brandt.id.au/roman-martyrology

collections:
  martyrs:
    output: true

email: veroicon@gmail.com

